# ============================
# Configuración de experimento
# ============================
experiment:
  model: "baseline"   # nombre corto del modelo (baseline, solid, etc.)
  seed: 42            # semilla fija para reproducibilidad

# ============================
# Configuración de datos
# ============================
data:
  train_dir: "/home/michell-alvarez/e_modelos/EF/Violencia/Train"
  test_dir: "/home/michell-alvarez/e_modelos/EF/Violencia/Test"
  classes: ["NonViolence", "Violence"]

  # Preprocesado
  frame_size: 112     # tamaño al que se redimensiona cada frame (ej. 112x112)
  num_frames: 16      # número de frames por video

# ============================
# Parámetros de entrenamiento
# ============================
training:
  batch_size: 8
  epochs: 30
  learning_rate: 0.001
  early_stop_patience: 10
  train_split: 0.8
  val_split: 0.2

# ============================
# Configuración del modelo
# ============================
model:
  name: "Baseline3DCNN"
  channels: [8, 16, 32]
  dropout: 0.3

# ============================
# Rutas base y derivadas
# ============================
paths:
  base_outputs: "outputs"          # carpeta raíz donde se crearán los run_id
  index_file: "data/video_index.csv"
  train_index: "data/train_index.csv"
  test_index: "data/test_index.csv"
  checkpoints: "checkpoints"      # se sobrescribirá dinámicamente por run_id
  logs: "logs/training.log"        # idem 
  #run_root: "outputs/baseline/2025-10-05_13-13-39"   # comenta si no es fijo
  
  


  

  
